language: java
jdk:
- oraclejdk8
- openjdk8
after_success:
- mvn clean test jacoco:report coveralls:report -DrepoToken=$RepoToken
env:
  global:
    secure: AtwSeo3I14VV5kNsgP1MzaREZM9FoAJ6NZCVbfy5BOeKIfm+a8MVUTc8OZjvhw2d8jeuUe/qd+AnoA3tpkuHYNrs6Zc2XxUyV4TzvFQrTf/fM2rSg/Ke8mgC/j3y8EJrs9iEi334Yhb8oerBjoUkHJ36MyHVT8+fCW3iH5qavD0QUqubUkLDXhMEgPp1ykUzarjQLt2FLGrmjF98JeetgfjpTSZeweV+I5ttJjh9lEcVLrdD3PDQm43fhrmwGLTXWp/a/3Ja5f/iz6M3mAObpgGOceHCBht9ipEaNPgc2iwOZ6obAnyD7yicGth/KlQAd4cZBpGus5msRvRxpMFKaW+ws5lrYajBLlwOlYI/Rf22fylktRZkQTSPyM/oRz5Z2zZ+BAlOpVZsXVCVL8yOCdFoUnFbeA3jYEmfzrzph6yB6uFIuybwq0Y8tb6bysm+0lkvWXpzsLgPh5QWQbeDy/12V2Dj5VW5kmwm/516Bg/7O/3kmp0Q+GuCTzsy2dWY9GoAZrdf2stnzV5HDLPr79gxSVRJ2JJuTUHbwN5MZzNgBcn23/XZ2GoanHrwT3WCpNtyrgphBU7vI32rohVt28pL7ZOC2Pzq9yYeDWJXd1w1op6cP8fkPN5Ewr338eb/UruNfZ6yIgjneccYhEjhFw9d3EoPSzZRzT24Da+rfNw=
